"""Core data types for DocScout.

The NL-document analogue of CodeScout's code-localization instance. Where
CodeScout localizes (file, module, function) targets in a repo, DocScout
locates section-level evidence in a corpus of natural-language documents and
extracts an answer. Section-level granularity is the unit of *reading* and the
unit of *evidence attribution* — both central to the read-budget contribution.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class ActionType(str, Enum):
    """The four discrete tool *types* the agent can invoke.

    Tool *type* is discrete; tool *args* (e.g. the search query string, or which
    candidate to read) are generated by the policy — see RESEARCH_BRIEF.md §六.
    """

    SEARCH = "search"
    READ = "read"
    EXPAND = "expand"
    ANSWER = "answer"


@dataclass
class Section:
    """A stable, locatable chunk of a document.

    Sections are pre-cut (stable ids) rather than dynamically re-chunked; the
    agent expands to *neighbors* via the EXPAND action (dynamic reading window
    over stable units) — see RESEARCH_BRIEF.md §四.
    """

    section_id: str  # human-stable id, e.g. "3"
    title: str
    text: str

    @property
    def token_len(self) -> int:
        """Rough token count (whitespace split). Good enough for budget accounting."""
        return len(self.text.split())


@dataclass
class Document:
    doc_id: str
    title: str
    sections: list[Section] = field(default_factory=list)

    def section_index(self, section_id: str) -> int:
        for i, s in enumerate(self.sections):
            if s.section_id == section_id:
                return i
        raise KeyError(f"section {section_id} not in doc {self.doc_id}")


@dataclass
class EvidenceSpan:
    """Gold evidence: a section that supports the answer. Section-locatable."""

    doc_id: str
    section_id: str


@dataclass
class QAInstance:
    """One training/eval example: a question over a corpus with gold answer+evidence."""

    instance_id: str
    question: str
    gold_answer: str
    gold_evidence: list[EvidenceSpan] = field(default_factory=list)
    docs: list[Document] = field(default_factory=list)
    meta: dict[str, Any] = field(default_factory=dict)

    def gold_sections(self) -> set[tuple[str, str]]:
        return {(e.doc_id, e.section_id) for e in self.gold_evidence}


@dataclass
class Action:
    """A parsed agent action."""

    type: ActionType
    args: dict[str, Any] = field(default_factory=dict)

    def to_log(self) -> str:
        if self.type == ActionType.SEARCH:
            return f"search({self.args.get('query', '')!r})"
        if self.type == ActionType.READ:
            return f"read({self.args.get('doc_id')}.{self.args.get('section_id')})"
        if self.type == ActionType.EXPAND:
            return f"expand({self.args.get('doc_id')}.{self.args.get('section_id')},{self.args.get('direction')})"
        if self.type == ActionType.ANSWER:
            return f"answer(...)"
        return str(self.type)


@dataclass
class StepResult:
    """Result of one env.step(): observation text + bookkeeping."""

    observation: str
    done: bool
    read_tokens: int = 0  # tokens of *document content* read into context this step
    info: dict[str, Any] = field(default_factory=dict)


@dataclass
class Trajectory:
    """A full rollout: actions, observations, final answer, bookkeeping."""

    instance_id: str
    actions: list[Action] = field(default_factory=list)
    observations: list[str] = field(default_factory=list)
    final_answer: str = ""
    final_evidence: list[EvidenceSpan] = field(default_factory=list)
    total_read_tokens: int = 0
    n_search: int = 0
    n_read: int = 0
    n_expand: int = 0
    n_steps: int = 0
    terminated_by: str = ""  # "answer" | "step_budget" | "token_budget"
    raw_messages: list[dict[str, Any]] = field(default_factory=list)
